// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using qnetwork_api.Data;

#nullable disable

namespace qnetwork_api.Migrations
{
    [DbContext(typeof(QNetworkContext))]
    partial class QNetworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("qnetwork_api.Models.IndustrialDevice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("IndustrialActuatorType")
                        .HasColumnType("int");

                    b.Property<int?>("IndustrialControllerType")
                        .HasColumnType("int");

                    b.Property<int>("IndustrialDeviceType")
                        .HasColumnType("int");

                    b.Property<int?>("IndustrialSensorType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("IndustrialDevices");
                });

            modelBuilder.Entity("qnetwork_api.Models.IndustrialDeviceNetworkMapping", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IndustrialDeviceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NetworkID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NetworkID");

                    b.HasIndex("IndustrialDeviceID", "NetworkID")
                        .IsUnique();

                    b.ToTable("IndustrialDeviceNetworkMappings");
                });

            modelBuilder.Entity("qnetwork_api.Models.Network", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ID");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("qnetwork_api.Models.IndustrialDeviceNetworkMapping", b =>
                {
                    b.HasOne("qnetwork_api.Models.IndustrialDevice", "IndustrialDevice")
                        .WithMany("NetworkMappings")
                        .HasForeignKey("IndustrialDeviceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("qnetwork_api.Models.Network", "Network")
                        .WithMany("IndustrialDeviceMappings")
                        .HasForeignKey("NetworkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndustrialDevice");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("qnetwork_api.Models.IndustrialDevice", b =>
                {
                    b.Navigation("NetworkMappings");
                });

            modelBuilder.Entity("qnetwork_api.Models.Network", b =>
                {
                    b.Navigation("IndustrialDeviceMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
